spring.application.name=AirBnbClone


# db configs
spring.datasource.url=jdbc:postgresql://localhost:5432/airbnb
spring.datasource.password=password
spring.datasource.username=postgres
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.servlet.context-path=/api/v1